sudo: required

language: node_js

node_js:
  - stable

dist: trusty

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng test --single-run --browser=ChromeHeadless

after_success:
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN
